### ISSUE TITLE
Unable to view `__call__` docstring?

### ISSUE THREAD

**Issue by billbrod** [flatironinstitute/nemos#201]
I'm unsure how we can pull up the docstring for `__call__`, which is pretty important for the basis objects. Is there something we're missing?

**Comment by BalzaniEdoardo** [comment]
I forgot to decorate one of the decorators with @wraps

**Comment by BalzaniEdoardo** [comment]
fixed with #209

**Comment by billbrod** [comment]
Oh nice, glad it was so easy to fix. Why is that the right thing to do?

**Comment by BalzaniEdoardo** [comment]
It's a decorator that is part of functools, which is the canonical way to
deal with the fact that the output function should inherit the same
docstrings as the  original.
Otherwise the docstrings of the wrapper function would show, but that's not
usually what people want, since a decorator can be applied to many
different functions.
