### ISSUE TITLE
Move to sphinx with md plugin

### ISSUE THREAD

**Issue by BalzaniEdoardo** [flatironinstitute/nemos#224]
Add more flexibility to the website styling by moving to sphinx [PyData theme](https://pydata-sphinx-theme.readthedocs.io/en/stable/).

Take advantage of [MyST parser](https://myst-parser.readthedocs.io/en/v0.17.1/sphinx/intro.html) to keep the tutorial as scripts.

**Comment by billbrod** [comment]
To be clear, in order to handle the tutorials as we're doing (plain-text documents that get converted to notebooks), we need not just myst, but [myst-nb](https://myst-nb.readthedocs.io/en/v0.13.2/index.html). What we want then is [to write notebooks in pure markdown](https://myst-nb.readthedocs.io/en/v0.13.2/use/myst.html#write-notebooks-in-pure-markdown). Note that this will require a change from how we're handling them now: mkdocs-gallery (like sphinx-gallery) has you write notebooks as *py* files, whereas myst-nb has you write them as *md* files. It's very possible that [jupytext](https://jupytext.readthedocs.io/en/latest/) can convert between these formats for us; it definitely can convert between ipynb and the myst-nb markdown formats, so at worst we can convert the mkdocs-gallery py file to ipynb, and then from that to myst-nb markdown. Just so we're not having to rewrite things manually.
